const listAll = [
    {
        sale: 66,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products13-min.jpg',
        type: 'Hữu cơ',
        title: 'Măng Cụt Hữu Cơ Từ Vĩnh Long',
        rate: 5,
        priceReal: 19,
        priceFake: 56,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products15-min.jpg',
        type: 'Hữu cơ',
        title: 'Gừng Tươi, Nguyên Củ, Hữu Cơ - 250gram',
        rate: 3,
        priceReal: 57,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products36-min.jpg',
        type: 'Hữu cơ',
        title: 'Lá Ổi Từ Cây Mọc Ở Miền Nam…',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products28-min.jpg',
        type: 'Hữu cơ',
        title: 'Trái Vải Tươi Đặc Sản Bắc Giang',
        rate: 5,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: 50,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products23-min.jpg',
        type: 'Rau',
        title: 'Bắp Cải Xanh Hữu Cơ',
        rate: 5,
        priceReal: 20,
        priceFake: 40,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products1-min.jpg',
        type: 'Hữu Cơ',
        title: 'Trái Nho Tươi Sapodilla Organic USA 100g',
        rate: 3,
        priceReal: 21,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products37-min.jpg',
        type: 'Hữu Cơ',
        title: 'Chanh Tuơi Và Chua Như Người Yêu Cũ',
        rate: 4,
        priceReal: 8,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products8-min.jpg',
        type: 'Thịt',
        title: 'Cánh Gà Chiên Giòn',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
];

const listMeat = [
    {
        sale: 63,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products20-min.jpg',
        type: 'Thịt Tươi Sống',
        title: 'Thịt Bò Hữu Cơ Ailen Nguyên Chất',
        rate: 5,
        priceReal: 19,
        priceFake: 56,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products26-min.jpg',
        type: 'Hữu cơ',
        title: 'Thịt Hầm Bò Angus USDA Choice - 1Kg',
        rate: 3,
        priceReal: 57,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products29-min.jpg',
        type: 'Hữu cơ',
        title: 'Đùi Gà Ngon Bổ Rẻ',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products10-min.jpg',
        type: 'Hữu cơ',
        title: 'Thịt Tươi Chất Lượng 1 Từ Mỹ 500g',
        rate: 5,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: 50,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products8-min.jpg',
        type: 'Rau',
        title: 'Cánh Gà Chiên Giòn',
        rate: 5,
        priceReal: 20,
        priceFake: 40,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products1-min.jpg',
        type: 'Hữu Cơ',
        title: 'Trái Nho Tươi Sapodilla Organic USA 100g',
        rate: 3,
        priceReal: 21,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products37-min.jpg',
        type: 'Hữu Cơ',
        title: 'Chanh Tuơi Và Chua Như Người Yêu Cũ',
        rate: 4,
        priceReal: 8,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products8-min.jpg',
        type: 'Thịt',
        title: 'Cánh Gà Chiên Giòn',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
];

const listVegetables = [
    {
        sale: 64,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products13-min.jpg',
        type: 'Hữu cơ',
        title: 'Măng Cụt Hữu Cơ Từ Vĩnh Long',
        rate: 5,
        priceReal: 19,
        priceFake: 56,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products15-min.jpg',
        type: 'Hữu cơ',
        title: 'Gừng Tươi, Nguyên Củ, Hữu Cơ - 250gram',
        rate: 3,
        priceReal: 57,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products36-min.jpg',
        type: 'Hữu cơ',
        title: 'Lá Ổi Từ Cây Mọc Ở Miền Nam…',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products28-min.jpg',
        type: 'Hữu cơ',
        title: 'Trái Vải Tươi Đặc Sản Bắc Giang',
        rate: 5,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: 50,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products23-min.jpg',
        type: 'Rau',
        title: 'Bắp Cải Xanh Hữu Cơ',
        rate: 5,
        priceReal: 20,
        priceFake: 40,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products1-min.jpg',
        type: 'Hữu Cơ',
        title: 'Trái Nho Tươi Sapodilla Organic USA 100g',
        rate: 3,
        priceReal: 21,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products37-min.jpg',
        type: 'Hữu Cơ',
        title: 'Chanh Tuơi Và Chua Như Người Yêu Cũ',
        rate: 4,
        priceReal: 8,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products8-min.jpg',
        type: 'Thịt',
        title: 'Cánh Gà Chiên Giòn',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
];

const listSnack = [
    {
        sale: 65,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products13-min.jpg',
        type: 'Hữu cơ',
        title: 'Măng Cụt Hữu Cơ Từ Vĩnh Long',
        rate: 5,
        priceReal: 19,
        priceFake: 56,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products15-min.jpg',
        type: 'Hữu cơ',
        title: 'Gừng Tươi, Nguyên Củ, Hữu Cơ - 250gram',
        rate: 3,
        priceReal: 57,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products36-min.jpg',
        type: 'Hữu cơ',
        title: 'Lá Ổi Từ Cây Mọc Ở Miền Nam…',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products28-min.jpg',
        type: 'Hữu cơ',
        title: 'Trái Vải Tươi Đặc Sản Bắc Giang',
        rate: 5,
        priceReal: 20,
        priceFake: null,
    },
    {
        sale: 50,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products23-min.jpg',
        type: 'Rau',
        title: 'Bắp Cải Xanh Hữu Cơ',
        rate: 5,
        priceReal: 20,
        priceFake: 40,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products1-min.jpg',
        type: 'Hữu Cơ',
        title: 'Trái Nho Tươi Sapodilla Organic USA 100g',
        rate: 3,
        priceReal: 21,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products37-min.jpg',
        type: 'Hữu Cơ',
        title: 'Chanh Tuơi Và Chua Như Người Yêu Cũ',
        rate: 4,
        priceReal: 8,
        priceFake: null,
    },
    {
        sale: null,
        img: 'https://wpblueskytech.com/orfarm/wp-content/uploads/2022/04/products8-min.jpg',
        type: 'Thịt',
        title: 'Cánh Gà Chiên Giòn',
        rate: 4,
        priceReal: 20,
        priceFake: null,
    },
];

export { listAll, listMeat, listVegetables, listSnack };
